---
title: "Silly Joining Data"
output: html_notebook
---

```{r}
pacman::p_load(tidyverse)

set.seed = 123

patients <- 
  data.frame(
    patient_id = 1:5,
    first_name = c("Homer", "Marge", "Bart", "Lisa", "Maggie"),
    last_name = rep("Simpson", 5)
  )

events <-
  data.frame(
    event_id = 1:10, 
    patient_id = c(1,3,5,2,1,1,2,1,3,1),
    event_type = c(
      "injury",
      "injury",
      "annual wellness",
      "physical",
      "influenza",
      "physical",
      "covid",
      "covid",
      "covid",
      "injury, radiation"
    ),
    event_date = as.Date(c(
      "2022-01-01",
      "2022-01-01",
      "2022-02-15",
      "2022-03-17",
      "2022-02-01",
      "2022-01-31",
      "2022-04-01",
      "2022-04-01",
      "2022-04-01",
      "2022-05-05"
    ))
)
```


# Inner Join
```{r}
patients |> inner_join(events, by = "patient_id")
```

# Left Join
```{r}
patients |> left_join(events, by = "patient_id")
```



# Right Join
```{r}
patients |> right_join(events, by = "patient_id")
```